userclouds/sdk-golang

authz/client.go
infra/jsonclient/client.go
infra/pagination/const.go
infra/pagination/options.go
infra/pagination/pager.go
infra/pagination/query.go
infra/pagination/types.go
infra/ucdb/basemodel.go

Updating the SDK - I'll want to update the tag as well when we push this to master for this repository.

re-sync SDK after pagination upgrade

---

.github/workflows/run-sample.yml

Syncing from userclouds/userclouds@c1a86b58ab4a386e4623e5078e16bd33301e2bd7

Sync monorepo state at "Fix sdk-golang CI running sample app"

---

infra/sdkclient/version.go
test/testlogtransport/transportTest.go

Syncing from userclouds/userclouds@d28ae4bc716218ccce9adfada53016156ab71a63

Sync monorepo state at "Go SDK sync: sync on changes to .rsync file"

---

infra/logtransports/logServerMapFetcher.go
infra/logtransports/options.go
infra/logtransports/transportFile.go
infra/logtransports/transportGoLog.go
infra/logtransports/transports.go
infra/namespace/color/color.go
infra/sdkclient/version.go

Syncing from userclouds/userclouds@55eb7d7d6987033611d83e96ea11e860230d2f42

Sync monorepo state at "Expose more logtransports files in golang sdk"

---

idp/userstore/selectorconfigparser/lexer.go
idp/userstore/selectorconfigparser/lexer.nex
idp/userstore/selectorconfigparser/parser.go
idp/userstore/selectorconfigparser/parser.y

Syncing from userclouds/userclouds@d760b27b0887e0cc003512f0b9ff62d6757aa93d

Sync monorepo state at "Adding ability to use "IS NULL" and "IS NOT NULL" operators"

---

.github/workflows/run-sample.yml
.github/workflows/sdkversion.yml
infra/logtransports/options.go
infra/logtransports/transportGoLog.go
infra/logtransports/transports.go

Syncing from userclouds/userclouds@5bb3ef7198c654f7bc1d17daa29565a9ceb0e631

Sync monorepo state at "Remove dependency on universe from go transport"

---

authz/attribute_validate_generated.go
authz/client.go
authz/edge_validate_generated.go
authz/edgetype_validate_generated.go
authz/object_validate_generated.go
authz/objecttype_validate_generated.go
idp/client.go
idp/paths/paths.go
idp/userstore/types.go
infra/cache/client/client_cache_inmemory.go
infra/cache/client/client_cache_redis.go
infra/oidc/providertype_constant_generated.go
infra/pagination/pager.go
infra/sdkclient/version.go

Syncing from userclouds/userclouds@78bd4feb51a84e2d224eb6fe32299aab9dabbc5a

Sync monorepo state at "Use gh instead of hub for repo syncs"

---

idp/userstore/types.go

Syncing from userclouds/userclouds@45216d7dac837a3776dd15001a60600fafef1b88

Sync monorepo state at "Expose error messages when creating accessors/mutators"

---

idp/userstore/types.go

Syncing from userclouds/userclouds@26cda8aa10aa8d4fc5d8ad5ba1442752f3f29733

Sync monorepo state at "Disallow system columns in mutators"

---

idp/client.go

Syncing from userclouds/userclouds@7a0795d0b0719e770a1d3df0d7141d6c1e84cf4a

Sync monorepo state at "Improve retention duration error handling and test coverage"

---

infra/cache/client/client_cache_api.go
infra/cache/client/client_cache_inmemory.go
infra/cache/client/client_cache_redis.go

Syncing from userclouds/userclouds@f77ca77e767ca786ff82723b99d5291b0e2ff815

Sync monorepo state at "Initial simple version of in memory store with invalidation"

---

idp/policy/models.go
idp/userstore/datatype_constant_generated.go

Syncing from userclouds/userclouds@9ca186e199c1e1e8482e513c66f810f651870496

Sync monorepo state at "add output type for transformers"

---

infra/assert/options.go

Syncing from userclouds/userclouds@eda6ce370c522f99300280cc51676cb2a9ef549f

Sync monorepo state at "DenyAll access policy and a few other simple fixes"

---

authz/client.go
infra/cache/client/client_cache_api.go
infra/cache/client/client_cache_inmemory.go
infra/cache/client/client_cache_redis.go
infra/cache/shared/cache_writethrough_sentinel_manager.go

Syncing from userclouds/userclouds@e61e3b716e8d2b7e25fe923f55bb7f143b8c4c49

Sync monorepo state at "Refactor cache ORM integration to use CacheProvider interface"

---

idp/policy/models.go
infra/ucerr/oautherror.go
infra/uctypes/messaging/email/emailaddress/address.go

Syncing from userclouds/userclouds@4a112315d28dba97cf0e5995599f303c9d2cecd2

Sync monorepo state at "fix leaking stack trace, and then lint / fix more"

---

authz/cache_name_provider.go
authz/cache_ttl_provider.go
authz/client.go
idp/policy/models.go
infra/cache/client/client_cache_api.go
infra/cache/client/client_cache_inmemory.go
infra/cache/client/client_cache_redis.go
infra/pagination/pager.go
infra/ucerr/oautherror.go
infra/uctypes/messaging/email/emailaddress/address.go

Syncing from userclouds/userclouds@c6311c65226c55ea68411750cbabb265482dafc1

Sync monorepo state at "Add caching to authz backend"

---

samples/basic/main.go
samples/userstore/main.go

Syncing from userclouds/userclouds@bb5919d022a776111064ce5c512db9285e0be058

Sync monorepo state at "Moving userstore golang sample to public repo"

---

idp/policy/constants.go
infra/sdkclient/version.go

Syncing from userclouds/userclouds@29318d15848b382f9b339e957f7165ebe7143d73

Sync monorepo state at "Add idp/policy/constants.go to public repo and prepare for release 0.7.6"

---

.github/actions/check-sdkversion/action.yml
authz/cache_name_provider.go
authz/client.go
authz/edge_validate_generated.go
authz/edgetype_validate_generated.go
authz/object_validate_generated.go
go.mod
go.sum
idp/client.go
idp/paths/paths.go
idp/policy/models.go
idp/tokenizer/policy_requests.go
idp/tokenizer_client.go
idp/userstore/types.go
infra/cache/client/client_cache_api.go
infra/cache/client/client_cache_inmemory.go
infra/cache/client/client_cache_redis.go
infra/logtransports/transportBackgroundIOWrapper.go
infra/logtransports/transportFile.go
infra/logtransports/transportLogServer.go
infra/request/context.go
infra/sdkclient/version.go
infra/ucdb/basemodel.go
infra/uclog/logger.go
samples/basic/authzhelper.go
samples/basic/main.go
test/testlogtransport/transportTest.go

Syncing from userclouds/userclouds@52ffe196270ea68ad469091bbcf57b913c657ed3

Sync monorepo state at "Don't allow blank names to be passed to authz.GetObjectForName()"

---

go.mod
infra/logtransports/shared.go
infra/logtransports/transportFile.go
infra/logtransports/transportGoLog.go
infra/logtransports/transports.go
infra/sdkclient/version.go
infra/uclog/events.go
infra/uclog/logger.go
samples/userstore/main.go

Syncing from userclouds/userclouds@93567be16dee3f9134a172f595aad895a2e2e51c

Sync monorepo state at "Retract v0.8.0, cut v0.8.1, update sample to use new names for modifi…"

---

authz/client.go
authz/models.go
idp/client.go
idp/tokenizer_client.go
infra/cache/client/client_cache_api.go
infra/cache/client/client_cache_inmemory.go
infra/cache/client/client_cache_redis.go
infra/jsonclient/client.go
infra/jsonclient/options.go
infra/logutils/constants.go
infra/namespace/region/regions.go
infra/request/context.go
infra/sdkclient/client.go
infra/sdkclient/version.go
infra/ucerr/error.go
infra/uclog/events.go
infra/uclog/logger.go
test/testlogtransport/transportTest.go

Syncing from userclouds/userclouds@1d1fe18ff412b5ee0c7b60c16bd675617dd7465d

Sync monorepo state at "Bump SDK version"

---

idp/policy/models.go
infra/assert/assert.go
infra/namespace/universe/universe.go

Syncing from userclouds/userclouds@dd81d5728a8ff064d41dcb3cac2aac8d61ffe2e6

Sync monorepo state at "DRY in tests - use common tools"

---

idp/userstore/types.go

Syncing from userclouds/userclouds@a57f08165e074395d7406d3e7f29c7639a454dfc

Sync monorepo state at "Add IsAuditLogged flag to accessors"

---

authz/client.go
infra/cache/client/client_cache_methods.go

Syncing from userclouds/userclouds@0c6bafd8e6defbdb74dbcb76f7c24b450828547b

Sync monorepo state at "cleanup cache prefix related stuff from userstore & plex code"

---

authz/models.go
samples/basic/main.go

Syncing from userclouds/userclouds@0388e17cadbca1e04e7896e6e847fe742f0cdbc6

Sync monorepo state at "Fix issue with SDK sample"

---

samples/basic/main.go

Syncing from userclouds/userclouds@89f09af296ea82055720a0cdb37a146898defe1a

Sync monorepo state at "Cleanup worker code"

---

authz/client.go
authz/models.go
idp/policy/models.go
idp/userstore/types.go
samples/basic/authzhelper.go
samples/basic/main.go

Syncing from userclouds/userclouds@4bed64bbefa302c83dc970bc52eccafe3403d54d

Sync monorepo state at "Use IfNotExists() for sdk-golang authz sample and cleanup objects to reduce errors from concurrent runs"

---

infra/oidc/clientcredentials.go

Syncing from userclouds/userclouds@8b6b3cc11a6637929be7652c5559c45f11e55022

Sync monorepo state at "Remove backward compat fields from message + add validation "

---

infra/oidc/clientcredentialstokensource_validate_generated.go

Syncing from userclouds/userclouds@0f2434dbd01aae0fc0c8b16944f9b692940e67a3

Sync monorepo state at "add clientcredentialstokensource_validate_generated to go sdk sync"

---

infra/oidc/clientcredentials.go
infra/oidc/clientcredentialstokensource_validate_generated.go

Syncing from userclouds/userclouds@a081ceda309a39d6fe3522e57760af050bf94ee3

Sync monorepo state at "Add validation to ClientCredentialsTokenSource"

---

idp/userstore/selectorconfigparser/lexer.go
idp/userstore/selectorconfigparser/lexer.nex
idp/userstore/selectorconfigparser/parser.go
idp/userstore/selectorconfigparser/parser.y
idp/userstore/selectorconfigparser/whereclause.go
idp/userstore/types.go

Syncing from userclouds/userclouds@73fbe9bcdac8933319eac964130fbc8a7cf7106c

Sync monorepo state at "Remove provision tool lambda TF infra"

---

test/testlogtransport/transportTest.go

Syncing from userclouds/userclouds@768df1e813b3c9e6b2eb4448f7ed9483b6619a93

Sync monorepo state at "Move log assertion helpers into transport test - make them emit useful info when they fail"

---

idp/client.go

Syncing from userclouds/userclouds@a61e49dee0ccac7c909d5a7de06bd571bef95db3

Sync monorepo state at "more validation on userstore requests structs"

---

idp/columnretentionduration_validate_generated.go
idp/durationunit_constant_generated.go
idp/executemutatorrequest_validate_generated.go
idp/retentionduration_validate_generated.go
idp/updatecolumnretentiondurationrequest_validate_generated.go
idp/updatecolumnretentiondurationsrequest_validate_generated.go
idp/userstore/datalifecyclestate_constant_generated.go

Syncing from userclouds/userclouds@35a9ca80de217c1efd6fdb18f3942fd07c39b1d5

Sync monorepo state at "Add new generated validators to go sdk sync file"

---

infra/cache/client_cache_api.go
infra/cache/client_cache_inmemory.go
infra/cache/client_cache_redis.go

Syncing from userclouds/userclouds@1262b3567d968216a65d7fb9fb64c3dc4d13154d

Sync monorepo state at "Remove cacheutil and use InvalidatingWrapper cache to detect changes …"

---

authz/client.go
authz/models.go

Syncing from userclouds/userclouds@a8165c9cda79d4683b26f56979428089e5cf92bb

Sync monorepo state at "pagination for edgetype and objecttype"

---

idp/tokenizer/policy_requests.go
idp/tokenizer_client.go

Syncing from userclouds/userclouds@2e318244a5e3ade556153debcbb4d1c16e30c2d9

Sync monorepo state at "Adding support for console.log in access policies / templates and passing through to console"

---

infra/cache/client_cache_methods.go

Syncing from userclouds/userclouds@74a167eff9c9e2df669f9c596a4a7ad3c747b30d

Sync monorepo state at "Log cache errors due to canceled context as warnings"

---

authz/models.go

Syncing from userclouds/userclouds@175c1c96ec1389ebda38af15c6a50216bcbbce41

Sync monorepo state at "revet breaking change"

---

infra/cache/client_cache_api.go
infra/cache/client_cache_inmemory.go
infra/cache/client_cache_redis.go

Syncing from userclouds/userclouds@1b25715a2d3491961952e61f04f22d3b21bb60e2

Sync monorepo state at "Change InvalidationHandler code to operate on single keys and update …"

---

infra/cache/client_cache_api.go

Syncing from userclouds/userclouds@f7e115ad64b7de6bcaf483043c2d2c3b14084969

Sync monorepo state at "fix typos"

---

infra/cache/api.go

Syncing from userclouds/userclouds@26ba85645dfe91ab5945e48dc2230fd471f740e0

Sync monorepo state at "Improve error messages in VerifyAndDecode, check claims before trying to get providers"

---

infra/namespace/region/regions.go

Syncing from userclouds/userclouds@db5c96a59875f8e2eaaaaef491dd5d36dcd43b1c

Sync monorepo state at "Add EU region to backend code"

---

infra/namespace/region/regions.go

Syncing from userclouds/userclouds@76e7f542d40fa08d516cab947acb041c5a84a4d9

Sync monorepo state at "Switch from eu-central-1 with eu-west-1"

---

infra/sdkclient/version.go

Syncing from userclouds/userclouds@3c00ee8760d3af871843b2b4eaae21f69acc2dad

Sync monorepo state at "Release v1.1.0 of sdk-golang"

---

CHANGELOG.md

Syncing from userclouds/userclouds@c3e99e7022fbffa087b24acbef06a51d60c5d0c6

Sync monorepo state at "update v1.4.0 changelog"

---

CHANGELOG.md
idp/policy/models.go
idp/userstore/types.go
infra/namespace/region/regions.go
infra/namespace/universe/universe.go
infra/pagination/options.go
infra/pagination/pager.go
infra/pagination/query.go
infra/pagination/types.go
infra/sdkclient/version.go
samples/userstore/main.go

Syncing from userclouds/userclouds@11b980faba6eb53dad59c54e0d9ac11204ce5b01

Sync monorepo state at "update python and golang SDKs to reflect current supported pagination options"
